channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=21.2.4
- pip:
  - pandas==2.2.3
  - matplotlib==3.9.2
  - seaborn==0.13.2
  - pickle4==0.0.1
  - numpy==1.26.4
  - mlflow==2.16
name: mlflow-env
